### ISSUE TITLE
[BUG]: new filesystem did not have specified protection_policy applied

### ISSUE THREAD

**Issue by bwdbethke** [dell/ansible-powerstore#20]
**Describe the bug**
Created a new filesystem and specified an existing protection_policy but the resulting filesystem did not have protection_policy specified.

**Steps to reproduce the behavior:**

0. create snapshot rules and protection policy (this works fine. just adding here for completeness)
```
powerstore_snapshotrules:
  - name: "snap-every-1d-keep-1w"
    interval: "One_Day"
    days_of_week:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday
    desired_retention: 192 # 7+1 days in hours
    state: present

powerstore_protectionpolicies:
  - name: "snap-every-1d-keep-1w"
    description: "Take snapshot daily and keep for 1 week"
    snapshotrules:
      - "snap-every-1d-keep-1w"
    snapshotrule_state: "present-in-policy"
    state: "present"
```

1. create new filesystem providing protection_policy value
```
powerstore_smb_filesystems:
  - filesystem_name: "test-fs"
    description: "SMB filesystem created by ansible"
    size: 8
    cap_unit: TB
    access_policy: NATIVE
    locking_policy: ADVISORY
    folder_rename_policy: ALL_FORBIDDEN
    protection_policy: "snap-every-1d-keep-1w"
    state: "present"
```

2. See task results that say filesystem was created successfully and mentions a value in protection_policy
```
changed: [san02] => (item={'filesystem_name': 'test-fs', 'description': 'SMB filesystem created by ansible', 'size': 8, 'cap_unit': 'TB', 'access_policy': 'NATIVE', 'locking_policy': 'ADVISORY', 'folder_rename_policy': 'ALL_FORBIDDEN', 'protection_policy': 'snap-every-1d-keep-1w', 'state': 'present'})
```

3. Get the details of the created filesystem via ansible to see the results list ` "protection_policy": null`

**Logs**
2022-11-02 12:53:23,163 filesystem.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2022-11-02 12:53:23,164 filesystem.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2022-11-02 12:53:23,164 filesystem.py INFO : Got Py4ps instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f13c04470a0>
2022-11-02 12:53:23,164 filesystem.py INFO : Got Py4ps instance for protection on PowerStore <PyPowerStore.protection.ProtectionFunctions object at 0x7f13c03f2550>
2022-11-02 12:53:23,548 filesystem.py INFO : Getting NAS Server details nas02
2022-11-02 12:53:24,430 filesystem.py INFO : Successfully got NAS Server details NNN from powerstore array name : san02 ,global id : 0
2022-11-02 12:53:24,431 filesystem.py INFO : Getting File System Details with filesystem_id None, filesystem_name test-fs , nas_server_id NNN
2022-11-02 12:53:24,770 filesystem.py INFO : Successfully Got FileSystem Details None
2022-11-02 12:53:24,770 filesystem.py INFO : FileSystem Details: None , To Modify False
2022-11-02 12:53:24,770 filesystem.py INFO : Attempting to create filesystem name test-fs
2022-11-02 12:53:31,776 filesystem.py INFO : Successfully Created FileSystem with details : {'id': 'XXX'}
2022-11-02 12:53:31,776 filesystem.py INFO : Getting File System Details with filesystem_id XXX, filesystem_name None , nas_server_id None
2022-11-02 12:53:32,096 filesystem.py INFO : Successfully Got FileSystem Details {'id': 'XXX', 'name': 'test-fs', 'description': 'SMB filesystem created by ansible', 'parent_id': None, 'filesystem_type': 'Primary', 'size_total': 8796093022208, 'size_used': 1621098496, 'access_policy': 'Native', 'locking_policy': 'Advisory', 'folder_rename_policy': 'All_Forbidden', 'is_smb_sync_writes_enabled': False, 'is_smb_op_locks_enabled': True, 'is_smb_no_notify_enabled': False, 'is_smb_notify_on_access_enabled': False, 'is_smb_notify_on_write_enabled': False, 'smb_notify_on_change_dir_depth': 512, 'is_async_MTime_enabled': False, 'is_quota_enabled': False, 'grace_period': 604800, 'default_hard_limit': 0, 'default_soft_limit': 0, 'creation_timestamp': None, 'expiration_timestamp': None, 'last_refresh_timestamp': None, 'last_writable_timestamp': None, 'is_modified': None, 'access_type': None, 'creator_type': None, 'filesystem_type_l10n': 'Primary File system', 'access_policy_l10n': 'Native', 'locking_policy_l10n': 'Advisory', 'folder_rename_policy_l10n': 'All Renames Forbidden', 'access_type_l10n': None, 'creator_type_l10n': None, 'nas_server': {'name': 'nas02', 'id': 'NNN'}, 'protection_policy': None}
2022-11-02 12:53:32,096 filesystem.py INFO : Checking if Modify required for filesystem 
2022-11-02 12:53:32,096 filesystem.py INFO : Modify Dict {}

**System Information:**
 - ansible [core 2.13.4]
 - python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
 -  jinja version = 3.1.2
