### ISSUE TITLE
[BUG]: Unsupported parameters for (dellemc.powerstore.filesystem) module: config_type, file_events_publishing_mode, host_io_size, is_async_mtime_enabled

### ISSUE THREAD

**Issue by bwdbethke** [dell/ansible-powerstore#26]
I'm getting errors from dellemc.powerstore.filesystem when I try to specify
- config_type
- is_async_mtime_enabled
- file_events_publishing_mode
- host_io_size

It doesn't seem to be recognizing those parameters.
I expected they should be working since #18 was resolved.

The specific msg I'm getting is:
```
"msg": "Unsupported parameters for (dellemc.powerstore.filesystem) module: config_type, file_events_publishing_mode, host_io_size, is_async_mtime_enabled. Supported parameters include: verifycert, smb_properties, access_policy, state, cap_unit, folder_rename_policy, filesystem_name, protection_policy, locking_policy, nas_server, user, timeout, size, filesystem_id, password, port, description, quota_defaults, array_ip."}
```

I'm trying to create a filesystem with the following:
```
  tasks:
    - name: Get details of NAS Server by name
      register: result_nas
      dellemc.powerstore.nasserver:
        array_ip: "{{ powerstore_array_ip }}"
        verifycert: "{{ powerstore_verify_cert }}"
        user: "{{ powerstore_user }}"
        password: "{{ powerstore_password }}"
        nas_server_name: "mynas"
        state: "present"

    - name: Create NFS FileSystem
      loop: "{{ powerstore_nfs_filesystems | default([]) }}"
      register: result_nfs_fs
      dellemc.powerstore.filesystem:
        array_ip: "{{ powerstore_array_ip }}"
        verifycert: "{{ powerstore_verify_cert }}"
        user: "{{ powerstore_user }}"
        password: "{{ powerstore_password }}"
        filesystem_name: "{{ item.filesystem_name }}"
        nas_server: "{{ result_nas.nasserver_details.name }}"
        description: "{{item.description | default(omit) }}"
        size: "{{ item.size }}"
        cap_unit: "{{ item.cap_unit | default(omit) }}"
        access_policy: "{{ item.access_policy | default(omit) }}"
        locking_policy: "{{ item.locking_policy | default(omit) }}"
        folder_rename_policy: "{{ item.folder_rename_policy | default(omit) }}"
        protection_policy: "{{ item.protection_policy | default(omit) }}"
        config_type: "{{ item.config_type | default(omit) }}"
        is_async_mtime_enabled: "{{ item.is_async_MTime_enabled | default(omit) }}"
        file_events_publishing_mode: "{{ item.file_events_publishing_mode | default(omit) }}"
        host_io_size: "{{ item.host_io_size | default(omit) }}"
        state: "{{ item.state | default(omit) }}"
```

I'm feeding in these vars:
```
  - filesystem_name: test-ansible-vmware-fs
    description: "Filesystem for VMware NFS datastore created by ansible"
    config_type: VMWARE
    size: 1
    cap_unit: TB
    host_io_size: VMWARE_8K
    is_async_MTime_enabled: true
    access_policy: NATIVE
    locking_policy: ADVISORY
    folder_rename_policy: SMB_FORBIDDEN
    protection_policy: snap-every-1d-keep-1w
    file_events_publishing_mode: NFS_ONLY
    state: present
```

FWIW, Here's how have been creating the filesystems via CLI since I can't get the ansible module to work for config_type `VMWARE` (or `VMware`)
```
pstcli file_system create -name test-cli-vmware-fs \
  -size_total 1099511627776 \
  -nas_server_name mynas \
  -description "VMware NFS datastore created by CLI" \
  -config_type VMware \
  -access_policy Native \
  -locking_policy Advisory \
  -folder_rename_policy SMB_Forbidden \
  -is_async_MTime_enabled true \
  -host_io_size VMware_8K 
```
