### ISSUE TITLE
[BUG]: After upgrading Powerstore to 4.1.0.0 Ansible stopped working

### ISSUE THREAD

**Issue by pandalec** [dell/ansible-powerstore#77]
**Describe the bug**
After upgrading Powerstore from 4.0.0.1/4.0.1.0 to 4.1.0.0 Ansible stopped working.

**To Reproduce**
1. Create Play:
```
    - name: Gather storage node facts
      dellemc.powerstore.info:
        array_ip: "{{ storage_ip_address }}"
        password: "{{ storage_password }}"
        user: "{{ storage_user }}"
        validate_certs: "{{ storage_validate_certs }}"
        gather_subset:
          - node
      register: storage_gather_facts_result
```
2. We have two Powerstores, both with Firmware 4.0.0.1/4.0.1.0 and get Powerstore facts like above.
3. Update one Powerstore to 4.1.0.0
4. Play stopped working with error HTTP code: 401

**Expected behavior**
Ansible should continue to work after Upgrade to Firmware 4.1.0.0

**Logs**
```
TASK [infrastructure.powerstore.storage_gather_facts : Gather storage node facts] *****************************************************************************************
fatal: [storage_01 -> deployment_node]: FAILED! => {
    "changed": false,
    "error_code": 1,
    "status_code": "401"
}

MSG:

Failed to get the clusters with error HTTP code: 401, Unauthorized [Access forbidden: Authentication required.]
ok: [storage_02 -> deployment_node]
```

**System Information (please complete the following information):**
 - OS/Version: Current Arch Linux with python-venv
 - Ansible Version 2.17.9
 - Python Version 3.10.16
 - Collection Version: dellemc.powerstore 3.7.0
